/* SPDX-License-Identifier: GPL-2.0-or-later */
#define TAPPING_TERM 180

#define QUICK_TAP_TERM 175
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

/* Miryoku */
#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_LIMIT_CHORD_TO_N_KEYS 4 /* GUI, Alt, Ctrl, Shift */
#define BILATERAL_COMBINATIONS_DELAY_MODS_THAT_MATCH (MOD_MASK_GUI|MOD_MASK_ALT|MOD_MASK_CTRL)
#define BILATERAL_COMBINATIONS_DELAY_MATCHED_MODS_BY 125  /* ms */
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 5   /* ms */
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 5 /* ms */
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 180  /* ms */

#define TAPPING_TOGGLE 3
