VIA_ENABLE = yes
BOOTMAGIC_ENABLE = yes
QMK_SETTINGS = yes

TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
CAPS_WORD_ENABLE = yes

# for BILATERAL_COMBINATIONS
DEFERRED_EXEC_ENABLE = yes
