/* SPDX-License-Identifier: GPL-2.0-or-later */
#define TAPPING_TERM 180
#define HM_TAPPING_TERM 250
#define HM_TAPPING_TERM_FAST 180
#define QUICK_TAP_TERM 175
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
